name: Motori i Zani Digjital

on:
  workflow_dispatch:
  schedule:
    # Fillon në 08:00 të mëngjesit dhe përfundon në 24:00 të natës sipas orës së Kosovës (tani ekzekutohet çdo 1 orë)
    - cron: '0 6-22 * * *'

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalo modulet
        run: pip install feedparser google-genai

      - name: Ekzekuto rishkrimin e lajmeve
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_API_KEY_2: ${{ secrets.GEMINI_API_KEY_2 }}
          GEMINI_API_KEY_3: ${{ secrets.GEMINI_API_KEY_3 }}
          GEMINI_API_KEY_4: ${{ secrets.GEMINI_API_KEY_4 }}
          GEMINI_API_KEY_5: ${{ secrets.GEMINI_API_KEY_5 }}
        run: python bot.py

      - name: Ruaj dhe publiko online
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lajmet.json
          git commit -m "U shtuan lajme te reja" || echo "S'ka lajme te reja"
          git push
