name: Motori i Zani Digjital

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ndiz_motorin]
  schedule:
    - cron: '17,47 * * * *' # E lëmë si plan B

permissions:
  contents: write

concurrency:
  group: zani-digjital-news
  cancel-in-progress: false

jobs:
  update-news:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalo modulet
        run: pip install feedparser groq trafilatura

      - name: Ekzekuto rishkrimin e lajmeve
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GROQ_API_KEY_2: ${{ secrets.GROQ_API_KEY_2 }}
          GROQ_API_KEY_3: ${{ secrets.GROQ_API_KEY_3 }}
          FACEBOOK_PAGE_TOKEN: ${{ secrets.FACEBOOK_PAGE_TOKEN }}
        run: python bot.py

      - name: Ruaj dhe publiko online
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"

          git add .

          if git diff --cached --quiet; then
            echo "S'ka lajme të reja"
            exit 0
          fi

          git commit -m "U shtuan lajme te reja automatikisht"
          git pull --rebase origin main
          git push
